/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-01-12 09:51:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.news;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import news.domain.Comments;
import news.domain.News;
import news.repository.NewsDAO;

public final class content_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


	NewsDAO newsDAO=new NewsDAO();

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/inc/header_link.jsp", Long.valueOf(1673483491866L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("news.domain.News");
    _jspx_imports_classes.add("news.domain.Comments");
    _jspx_imports_classes.add("news.repository.NewsDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

	String news_idx=request.getParameter("news_idx");
	News news=newsDAO.select(Integer.parseInt(news_idx));
	out.print(news);
	out.print("<br>댓글 갯수"+news.getCommentsList().size());

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>상세보기</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.1/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$($(\"button\")[0]).click(function() { //수정버튼\r\n");
      out.write("			$(\"#form1\").attr({\r\n");
      out.write("				\"action\" : \"/news/edit\",\r\n");
      out.write("				\"method\" : \"post\"\r\n");
      out.write("			});\r\n");
      out.write("			$(\"#form1\").submit();\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$($(\"button\")[1]).click(function() { //삭제버튼\r\n");
      out.write("			$(\"#form1\").attr({\r\n");
      out.write("				\"action\" : \"/news/del\",\r\n");
      out.write("				\"method\" : \"post\"\r\n");
      out.write("			});\r\n");
      out.write("			$(\"#form1\").submit();\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		$($(\"button\")[2]).click(function() {//목록버튼\r\n");
      out.write("			$(location).attr(\"href\", \"/news/list.jsp\");\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		//댓글 등록 버튼 이벤트 연결\r\n");
      out.write("		$(\"#form2 button\").click(function(){\r\n");
      out.write("			$(\"#form2\").attr({\r\n");
      out.write("				\"action\":\"/comments/regist\",\r\n");
      out.write("				\"method\":\"post\"\r\n");
      out.write("			});\r\n");
      out.write("			$(\"#form2\").submit();\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container mt-3 border\">\r\n");
      out.write("		<h2 class=\"text-center\">상세보기</h2>\r\n");
      out.write("		<form id=\"form1\">\r\n");
      out.write("			<input type=\"hidden\" name=\"news_idx\" value=\"");
      out.print(news.getNews_idx());
      out.write("\">\r\n");
      out.write("			<input type=\"hidden\" name=\"commentsSize\" value=\"");
      out.print(news.getCommentsList().size());
      out.write("\">\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<input type=\"text\" class=\"form-control\" value=\"");
      out.print(news.getTitle() );
      out.write("\"\r\n");
      out.write("					name=\"title\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<input type=\"text\" class=\"form-control\" value=\"");
      out.print(news.getWriter() );
      out.write("\"\r\n");
      out.write("					name=\"writer\">\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<textarea class=\"form-control\" placeholder=\"내용입력\" name=\"content\">");
      out.print(news.getContent() );
      out.write("</textarea>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"form-group text-center\">\r\n");
      out.write("				<button type=\"button\" class=\"btn btn-secondary\">수정</button>\r\n");
      out.write("				<button type=\"button\" class=\"btn btn-secondary\">삭제</button>\r\n");
      out.write("				<button type=\"button\" class=\"btn btn-secondary\">목록</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("		<form id=\"form2\">\r\n");
      out.write("			<input type=\"hidden\" name=\"news_idx\" value=\"");
      out.print(news.getNews_idx());
      out.write("\">\r\n");
      out.write("			<div class=\"form-group row\">\r\n");
      out.write("				<div class=\"col-md-6\">\r\n");
      out.write("					<input type=\"text\" class=\"form-control\" placeholder=\"Enter title\" name=\"msg\">\r\n");
      out.write("					</div>\r\n");
      out.write("				<div class=\"col-md-4\">\r\n");
      out.write("					<input type=\"text\" class=\"form-control\" placeholder=\"Enter title\" name=\"author\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-2\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-secondary\">댓글등록</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("		<table class=\"table table-hover\">\r\n");
      out.write("			<thead>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>댓글 메세지</th>\r\n");
      out.write("					<th>작성자</th>\r\n");
      out.write("					<th>등록일</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</thead>\r\n");
      out.write("			<tbody>\r\n");
      out.write("			");
for(int i=0;i<news.getCommentsList().size();i++){ 
      out.write("\r\n");
      out.write("			");
Comments comments=news.getCommentsList().get(i); 
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>");
      out.print(comments.getMsg());
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(comments.getAuthor() );
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(comments.getWritedate() );
      out.write("</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			");
} 
      out.write("	\r\n");
      out.write("			</tbody>\r\n");
      out.write("		</table>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
