/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-01-25 05:42:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.jspshop.domain.Admin;

public final class registForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/admin/inc/footer_link.jsp", Long.valueOf(1674306066000L));
    _jspx_dependants.put("/admin/inc/footer.jsp", Long.valueOf(1674306066000L));
    _jspx_dependants.put("/admin/inc/sidebar_rigth.jsp", Long.valueOf(1674306068000L));
    _jspx_dependants.put("/admin/inc/header_link.jsp", Long.valueOf(1674618335327L));
    _jspx_dependants.put("/admin/inc/preloader.jsp", Long.valueOf(1674306066000L));
    _jspx_dependants.put("/admin/inc/sidebar_left.jsp", Long.valueOf(1674306066000L));
    _jspx_dependants.put("/admin/inc/navbar.jsp", Long.valueOf(1674306066000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.jspshop.domain.Admin");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String[] sizeList = {"XS", "S", "M", "L", "XL", "XXL"};
String[] colorList = {"베이지", "네이비", "블랙", "화이트"};

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>AdminLTE 3 | 상품등록</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Google Font: Source Sans Pro -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback\">\r\n");
      out.write("<!-- Font Awesome -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/admin/plugins/fontawesome-free/css/all.min.css\">\r\n");
      out.write("<!-- Ionicons -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css\">\r\n");
      out.write("<!-- Tempusdominus Bootstrap 4 -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"/admin/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css\">\r\n");
      out.write("<!-- iCheck -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"/admin/plugins/icheck-bootstrap/icheck-bootstrap.min.css\">\r\n");
      out.write("<!-- JQVMap -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/admin/plugins/jqvmap/jqvmap.min.css\">\r\n");
      out.write("<!-- Theme style -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/admin/dist/css/adminlte.min.css\">\r\n");
      out.write("<!-- overlayScrollbars -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"/admin/plugins/overlayScrollbars/css/OverlayScrollbars.min.css\">\r\n");
      out.write("<!-- Daterange picker -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"/admin/plugins/daterangepicker/daterangepicker.css\">\r\n");
      out.write("<!-- summernote -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/admin/plugins/summernote/summernote-bs4.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- React -->\r\n");
      out.write("<script src=\"https://unpkg.com/react@18/umd/react.development.js\" crossorigin></script>\r\n");
      out.write("<script src=\"https://unpkg.com/react-dom@18/umd/react-dom.development.js\" crossorigin></script>\r\n");
      out.write("<script src=\"https://unpkg.com/@babel/standalone/babel.min.js\"></script>\r\n");
      out.write("<!-- Vue -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/vue@2.7.14/dist/vue.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"hold-transition sidebar-mini layout-fixed\">\r\n");
      out.write("	<div class=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Preloader -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<div class=\"preloader flex-column justify-content-center align-items-center\">\r\n");
      out.write("    <img class=\"animation__shake\" src=\"/admin/dist/img/AdminLTELogo.png\" alt=\"AdminLTELogo\" height=\"60\" width=\"60\">\r\n");
      out.write(" </div>");
      out.write("\r\n");
      out.write("		<!-- Navbar -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write(" <nav class=\"main-header navbar navbar-expand navbar-white navbar-light\">\r\n");
      out.write("    <!-- Left navbar links -->\r\n");
      out.write("    <ul class=\"navbar-nav\">\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" data-widget=\"pushmenu\" href=\"#\" role=\"button\"><i class=\"fas fa-bars\"></i></a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item d-none d-sm-inline-block\">\r\n");
      out.write("        <a href=\"index3.html\" class=\"nav-link\">Home</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item d-none d-sm-inline-block\">\r\n");
      out.write("        <a href=\"#\" class=\"nav-link\">Contact</a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("    <!-- Right navbar links -->\r\n");
      out.write("    <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("      <!-- Navbar Search -->\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" data-widget=\"navbar-search\" href=\"#\" role=\"button\">\r\n");
      out.write("          <i class=\"fas fa-search\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"navbar-search-block\">\r\n");
      out.write("          <form class=\"form-inline\">\r\n");
      out.write("            <div class=\"input-group input-group-sm\">\r\n");
      out.write("              <input class=\"form-control form-control-navbar\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("              <div class=\"input-group-append\">\r\n");
      out.write("                <button class=\"btn btn-navbar\" type=\"submit\">\r\n");
      out.write("                  <i class=\"fas fa-search\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("                <button class=\"btn btn-navbar\" type=\"button\" data-widget=\"navbar-search\">\r\n");
      out.write("                  <i class=\"fas fa-times\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("\r\n");
      out.write("      <!-- Messages Dropdown Menu -->\r\n");
      out.write("      <li class=\"nav-item dropdown\">\r\n");
      out.write("        <a class=\"nav-link\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("          <i class=\"far fa-comments\"></i>\r\n");
      out.write("          <span class=\"badge badge-danger navbar-badge\">3</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-menu dropdown-menu-lg dropdown-menu-right\">\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <!-- Message Start -->\r\n");
      out.write("            <div class=\"media\">\r\n");
      out.write("              <img src=\"/admin/dist/img/user1-128x128.jpg\" alt=\"User Avatar\" class=\"img-size-50 mr-3 img-circle\">\r\n");
      out.write("              <div class=\"media-body\">\r\n");
      out.write("                <h3 class=\"dropdown-item-title\">\r\n");
      out.write("                  Brad Diesel\r\n");
      out.write("                  <span class=\"float-right text-sm text-danger\"><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("                </h3>\r\n");
      out.write("                <p class=\"text-sm\">Call me whenever you can...</p>\r\n");
      out.write("                <p class=\"text-sm text-muted\"><i class=\"far fa-clock mr-1\"></i> 4 Hours Ago</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Message End -->\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <!-- Message Start -->\r\n");
      out.write("            <div class=\"media\">\r\n");
      out.write("              <img src=\"/admin/dist/img/user8-128x128.jpg\" alt=\"User Avatar\" class=\"img-size-50 img-circle mr-3\">\r\n");
      out.write("              <div class=\"media-body\">\r\n");
      out.write("                <h3 class=\"dropdown-item-title\">\r\n");
      out.write("                  John Pierce\r\n");
      out.write("                  <span class=\"float-right text-sm text-muted\"><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("                </h3>\r\n");
      out.write("                <p class=\"text-sm\">I got your message bro</p>\r\n");
      out.write("                <p class=\"text-sm text-muted\"><i class=\"far fa-clock mr-1\"></i> 4 Hours Ago</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Message End -->\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <!-- Message Start -->\r\n");
      out.write("            <div class=\"media\">\r\n");
      out.write("              <img src=\"/admin/dist/img/user3-128x128.jpg\" alt=\"User Avatar\" class=\"img-size-50 img-circle mr-3\">\r\n");
      out.write("              <div class=\"media-body\">\r\n");
      out.write("                <h3 class=\"dropdown-item-title\">\r\n");
      out.write("                  Nora Silvester\r\n");
      out.write("                  <span class=\"float-right text-sm text-warning\"><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("                </h3>\r\n");
      out.write("                <p class=\"text-sm\">The subject goes here</p>\r\n");
      out.write("                <p class=\"text-sm text-muted\"><i class=\"far fa-clock mr-1\"></i> 4 Hours Ago</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Message End -->\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item dropdown-footer\">See All Messages</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <!-- Notifications Dropdown Menu -->\r\n");
      out.write("      <li class=\"nav-item dropdown\">\r\n");
      out.write("        <a class=\"nav-link\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("          <i class=\"far fa-bell\"></i>\r\n");
      out.write("          <span class=\"badge badge-warning navbar-badge\">15</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-menu dropdown-menu-lg dropdown-menu-right\">\r\n");
      out.write("          <span class=\"dropdown-item dropdown-header\">15 Notifications</span>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <i class=\"fas fa-envelope mr-2\"></i> 4 new messages\r\n");
      out.write("            <span class=\"float-right text-muted text-sm\">3 mins</span>\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <i class=\"fas fa-users mr-2\"></i> 8 friend requests\r\n");
      out.write("            <span class=\"float-right text-muted text-sm\">12 hours</span>\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <i class=\"fas fa-file mr-2\"></i> 3 new reports\r\n");
      out.write("            <span class=\"float-right text-muted text-sm\">2 days</span>\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item dropdown-footer\">See All Notifications</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" data-widget=\"fullscreen\" href=\"#\" role=\"button\">\r\n");
      out.write("          <i class=\"fas fa-expand-arrows-alt\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" data-widget=\"control-sidebar\" data-controlsidebar-slide=\"true\" href=\"#\" role=\"button\">\r\n");
      out.write("          <i class=\"fas fa-th-large\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </nav>\r\n");
      out.write("\r\n");
      out.write("		<!-- /.navbar -->\r\n");
      out.write("\r\n");
      out.write("		<!-- Main Sidebar Container -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<aside class=\"main-sidebar sidebar-dark-primary elevation-4\">\r\n");
      out.write("	<!-- Brand Logo -->\r\n");
      out.write("	<a href=\"index3.html\" class=\"brand-link\"> <img\r\n");
      out.write("		src=\"/admin/dist/img/AdminLTELogo.png\" alt=\"AdminLTE Logo\"\r\n");
      out.write("		class=\"brand-image img-circle elevation-3\" style=\"opacity: .8\">\r\n");
      out.write("		<span class=\"brand-text font-weight-light\">AdminLTE 3</span>\r\n");
      out.write("	</a>\r\n");
      out.write("\r\n");
      out.write("	<!-- Sidebar -->\r\n");
      out.write("	<div class=\"sidebar\">\r\n");
      out.write("		<!-- Sidebar user panel (optional) -->\r\n");
      out.write("		<div class=\"user-panel mt-3 pb-3 mb-3 d-flex\">\r\n");
      out.write("			<div class=\"image\">\r\n");
      out.write("				<img src=\"/admin/dist/img/user2-160x160.jpg\"\r\n");
      out.write("					class=\"img-circle elevation-2\" alt=\"User Image\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"info\">\r\n");
      out.write("\r\n");
      out.write("				<a href=\"#\" class=\"d-block\">");
      out.print("zino");
      out.write("</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- SidebarSearch Form -->\r\n");
      out.write("		<div class=\"form-inline\">\r\n");
      out.write("			<div class=\"input-group\" data-widget=\"sidebar-search\">\r\n");
      out.write("				<input class=\"form-control form-control-sidebar\" type=\"search\"\r\n");
      out.write("					placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("				<div class=\"input-group-append\">\r\n");
      out.write("					<button class=\"btn btn-sidebar\">\r\n");
      out.write("						<i class=\"fas fa-search fa-fw\"></i>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Sidebar Menu -->\r\n");
      out.write("		<nav class=\"mt-2\">\r\n");
      out.write("			<ul class=\"nav nav-pills nav-sidebar flex-column\"\r\n");
      out.write("				data-widget=\"treeview\" role=\"menu\" data-accordion=\"false\">\r\n");
      out.write("\r\n");
      out.write("				<!-- Add icons to the links using the .nav-icon class\r\n");
      out.write("               with font-awesome or any other icon font library \r\n");
      out.write("               nav-item menu-open : 네비게이션 열려있게 해줌\r\n");
      out.write("               -->\r\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\" class=\"nav-link active\"> <i\r\n");
      out.write("						class=\"nav-icon fas fa-tachometer-alt\"></i>\r\n");
      out.write("						<p>\r\n");
      out.write("							상점관리 <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("						</p>\r\n");
      out.write("				</a>\r\n");
      out.write("					<ul class=\"nav nav-treeview\">\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index.html\"\r\n");
      out.write("							class=\"nav-link active\"> <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v1</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index2.html\" class=\"nav-link\">\r\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v2</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index3.html\" class=\"nav-link\">\r\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v3</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("				\r\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\" class=\"nav-link active\"> <i\r\n");
      out.write("						class=\"nav-icon fas fa-tachometer-alt\"></i>\r\n");
      out.write("						<p>\r\n");
      out.write("							상품관리 <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("						</p>\r\n");
      out.write("				</a>\r\n");
      out.write("					<ul class=\"nav nav-treeview\">\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"/admin/product/registForm.jsp\"\r\n");
      out.write("							class=\"nav-link\"> <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>상품등록</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index2.html\" class=\"nav-link\">\r\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>일괄등록</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\" class=\"nav-link active\"> <i\r\n");
      out.write("						class=\"nav-icon fas fa-tachometer-alt\"></i>\r\n");
      out.write("						<p>\r\n");
      out.write("							회원관리 <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("						</p>\r\n");
      out.write("				</a>\r\n");
      out.write("					<ul class=\"nav nav-treeview\">\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index.html\"\r\n");
      out.write("							class=\"nav-link active\"> <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v1</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index2.html\" class=\"nav-link\">\r\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v2</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index3.html\" class=\"nav-link\">\r\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v3</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\" class=\"nav-link active\"> <i\r\n");
      out.write("						class=\"nav-icon fas fa-tachometer-alt\"></i>\r\n");
      out.write("						<p>\r\n");
      out.write("							주문관리 <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("						</p>\r\n");
      out.write("				</a>\r\n");
      out.write("					<ul class=\"nav nav-treeview\">\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index.html\"\r\n");
      out.write("							class=\"nav-link active\"> <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v1</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index2.html\" class=\"nav-link\">\r\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v2</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index3.html\" class=\"nav-link\">\r\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v3</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\" class=\"nav-link active\"> <i\r\n");
      out.write("						class=\"nav-icon fas fa-tachometer-alt\"></i>\r\n");
      out.write("						<p>\r\n");
      out.write("							통계관리 <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("						</p>\r\n");
      out.write("				</a>\r\n");
      out.write("					<ul class=\"nav nav-treeview\">\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index.html\"\r\n");
      out.write("							class=\"nav-link active\"> <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v1</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index2.html\" class=\"nav-link\">\r\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v2</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index3.html\" class=\"nav-link\">\r\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v3</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\" class=\"nav-link active\"> <i\r\n");
      out.write("						class=\"nav-icon fas fa-tachometer-alt\"></i>\r\n");
      out.write("						<p>\r\n");
      out.write("							고객센터 <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("						</p>\r\n");
      out.write("				</a>\r\n");
      out.write("					<ul class=\"nav nav-treeview\">\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index.html\"\r\n");
      out.write("							class=\"nav-link active\"> <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v1</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index2.html\" class=\"nav-link\">\r\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v2</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index3.html\" class=\"nav-link\">\r\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v3</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("		</nav>\r\n");
      out.write("		<!-- /.sidebar-menu -->\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- /.sidebar -->\r\n");
      out.write("</aside>");
      out.write("\r\n");
      out.write("		<!-- Content Wrapper. Contains page content -->\r\n");
      out.write("		<div class=\"content-wrapper\">\r\n");
      out.write("			<!-- Content Header (Page header) -->\r\n");
      out.write("			<div class=\"content-header\">\r\n");
      out.write("				<div class=\"container-fluid\">\r\n");
      out.write("					<div class=\"row mb-2\">\r\n");
      out.write("						<div class=\"col-sm-6\">\r\n");
      out.write("							<h1 class=\"m-0\">상품등록</h1>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- /.col -->\r\n");
      out.write("						<div class=\"col-sm-6\">\r\n");
      out.write("							<ol class=\"breadcrumb float-sm-right\">\r\n");
      out.write("								<li class=\"breadcrumb-item\"><a href=\"#\">Home</a></li>\r\n");
      out.write("								<li class=\"breadcrumb-item active\">Dashboard v1</li>\r\n");
      out.write("							</ol>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- /.col -->\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- /.row -->\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- /.container-fluid -->\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- /.content-header -->\r\n");
      out.write("\r\n");
      out.write("			<!-- Main content -->\r\n");
      out.write("			<section class=\"content\">\r\n");
      out.write("				<div class=\"container-fluid\">\r\n");
      out.write("					<div class=\"col\">\r\n");
      out.write("						<form id=\"form1\">\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<select id=\"category\" class=\"form-control\" placeholder=\"카테고리\">\r\n");
      out.write("								</select>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<input type=\"email\" class=\"form-control\" id=\"product_name\" placeholder=\"상품명\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<input type=\"email\" class=\"form-control\" id=\"brand\" placeholder=\"브랜드\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<input type=\"number\" class=\"form-control\" id=\"price\" placeholder=\"가격\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<input type=\"number\" class=\"form-control\" id=\"discount\" placeholder=\"할인가\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								");
for (int i=0;i<sizeList.length;i++) {
      out.write("\r\n");
      out.write("								<div class=\"icheck-primary d-inline\">\r\n");
      out.write("									<input type=\"checkbox\" id=\"size");
      out.print(i );
      out.write("\" name=\"size\" value=\"");
      out.print(sizeList[i]);
      out.write("\">\r\n");
      out.write("									<label for=\"size");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(sizeList[i]);
      out.write("</label>\r\n");
      out.write("								</div>\r\n");
      out.write("								");
}
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								");
for (int i=0;i<colorList.length;i++) {
      out.write("\r\n");
      out.write("								<div class=\"icheck-primary d-inline\">\r\n");
      out.write("									<input type=\"checkbox\" id=\"color");
      out.print(i );
      out.write("\" name=\"color\" value=\"");
      out.print(colorList[i]);
      out.write("\">\r\n");
      out.write("									<label for=\"color");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(colorList[i]);
      out.write("</label>\r\n");
      out.write("								</div>\r\n");
      out.write("								");
}
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<textarea id=\"detail\" type=\"email\" class=\"form-control\" placeholder=\"상세\"></textarea>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<div class=\"custom-file\">\r\n");
      out.write("							<input type=\"file\" class=\"custom-file-input\" multiple=\"multiple\" id=\"file\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<span class=\"btn btn-success col-12 fileinput-button\" onClick=\"triggerFile()\">\r\n");
      out.write("                                 <i class=\"fas fa-plus\"> 파일을 추가하세요</i>\r\n");
      out.write("                             </span>\r\n");
      out.write("						</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"row form-group\" id=\"preview\">\r\n");
      out.write("						미리보기 영역\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-warning\" id=\"bt_regist\">등록</button>\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-warning\" id=\"bt_list\">목록</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- /.container-fluid -->\r\n");
      out.write("		</section>\r\n");
      out.write("		<!-- /.content -->\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- /.content-wrapper -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<footer class=\"main-footer\">\r\n");
      out.write("	<strong>Copyright &copy; 2014-2021 <a\r\n");
      out.write("		href=\"https://adminlte.io\">AdminLTE.io</a>.\r\n");
      out.write("	</strong> All rights reserved.\r\n");
      out.write("	<div class=\"float-right d-none d-sm-inline-block\">\r\n");
      out.write("		<b>Version</b> 3.2.0\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("	<!-- Control Sidebar -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<aside class=\"control-sidebar control-sidebar-dark\">\r\n");
      out.write("	<!-- Control sidebar content goes here -->\r\n");
      out.write("	여기가 우측 서랍장\r\n");
      out.write("</aside>");
      out.write("\r\n");
      out.write("	<!-- /.control-sidebar -->\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- ./wrapper -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<!-- jQuery -->\r\n");
      out.write("	<script src=\"/admin/plugins/jquery/jquery.min.js\"></script>\r\n");
      out.write("	<!-- jQuery UI 1.11.4 -->\r\n");
      out.write("	<script src=\"/admin/plugins/jquery-ui/jquery-ui.min.js\"></script>\r\n");
      out.write("	<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->\r\n");
      out.write("	<script>\r\n");
      out.write("		//$.widget.bridge('uibutton', $.ui.button)\r\n");
      out.write("	</script>\r\n");
      out.write("	<!-- Bootstrap 4 -->\r\n");
      out.write("	<script src=\"/admin/plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<!-- ChartJS -->\r\n");
      out.write("	<script src=\"/admin/plugins/chart.js/Chart.min.js\"></script>\r\n");
      out.write("	<!-- Sparkline -->\r\n");
      out.write("	<script src=\"/admin/plugins/sparklines/sparkline.js\"></script>\r\n");
      out.write("	<!-- JQVMap -->\r\n");
      out.write("	<script src=\"/admin/plugins/jqvmap/jquery.vmap.min.js\"></script>\r\n");
      out.write("	<script src=\"/admin/plugins/jqvmap/maps/jquery.vmap.usa.js\"></script>\r\n");
      out.write("	<!-- jQuery Knob Chart -->\r\n");
      out.write("	<script src=\"/admin/plugins/jquery-knob/jquery.knob.min.js\"></script>\r\n");
      out.write("	<!-- daterangepicker -->\r\n");
      out.write("	<script src=\"/admin/plugins/moment/moment.min.js\"></script>\r\n");
      out.write("	<script src=\"/admin/plugins/daterangepicker/daterangepicker.js\"></script>\r\n");
      out.write("	<!-- Tempusdominus Bootstrap 4 -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"/admin/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js\"></script>\r\n");
      out.write("	<!-- Summernote -->\r\n");
      out.write("	<script src=\"/admin/plugins/summernote/summernote-bs4.min.js\"></script>\r\n");
      out.write("	<!-- overlayScrollbars -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"/admin/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js\"></script>\r\n");
      out.write("	<!-- AdminLTE App -->\r\n");
      out.write("	<script src=\"/admin/dist/js/adminlte.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<!-- AdminLTE for demo purposes -->\r\n");
      out.write("	<!-- 	<script src=\"/admin/dist/js/demo.js\"></script> -->\r\n");
      out.write("	\r\n");
      out.write("	<!-- AdminLTE dashboard demo (This is only for demo purposes) -->\r\n");
      out.write("	<!-- <script src=\"/admin/dist/js/pages/dashboard.js\"></script> -->");
      out.write("\r\n");
      out.write("	<script type=\"text/babel\">\r\n");
      out.write("		function ImgBox(props){\r\n");
      out.write("			return (\r\n");
      out.write("				<div className={\"col-sm-2 border\"}>\r\n");
      out.write("					<div>\r\n");
      out.write("						<a href=\"#\" onClick={(e)=>removeImg(e, props.index)}>x</a>					\r\n");
      out.write("					</div>\r\n");
      out.write("					<img src={props.src} width=\"100px\"/>\r\n");
      out.write("				</div>\r\n");
      out.write("			);\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		function triggerFile(){\r\n");
      out.write("			//파일 컴포넌트를 대상으로 클릭 효과를 냄 (간접적 효과)\r\n");
      out.write("			$(\"#file\").trigger(\"click\");\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("		function regist(){\r\n");
      out.write("			//이미지 미리보기 기능은 단순히 우리만의 배열처리였을뿐 input type=\"file\" 컴포넌트는 여전히 유저가 선택한 이미지 정보를 유지함\r\n");
      out.write("			//따라서 기존의 폼을 그대로 전송하면 안되고, 개발자가 폼에 들어갈 파일을 직접 제어해야 함 이 방법을 jquery가 지원해줌\r\n");
      out.write("			let formData=new FormData();\r\n");
      out.write("			\r\n");
      out.write("			console.log(\"전송하기 위해 넣은 파일의 수는 \", fileList.length);\r\n");
      out.write("			\r\n");
      out.write("			//파일뿐만 아니라 파라미터 등을 심을 수 있음\r\n");
      out.write("			//formData 사용 이유 : 개발자가 주도해서 넣고 뺴기 위해\r\n");
      out.write("			formData.append(\"category_idx\", $(\"#category\").val());\r\n");
      out.write("			formData.append(\"product_name\", $(\"#product_name\").val());\r\n");
      out.write("			formData.append(\"brand\", $(\"#brand\").val());\r\n");
      out.write("			formData.append(\"price\", $(\"#price\").val());\r\n");
      out.write("			formData.append(\"discount\", $(\"#discount\").val());\r\n");
      out.write("			\r\n");
      out.write("			//체크된 것만 데이터를 모으자\r\n");
      out.write("			let sizeCheckedArr=[];  //체크된 데이터만 모을 빈 배열\r\n");
      out.write("			for(let i=0;i<$(\"input[name='size']\").length;i++){\r\n");
      out.write("				if($($(\"input[name='size']\")[i]).is(\":checked\")){\r\n");
      out.write("					//배열에 값 넣기\r\n");
      out.write("					sizeCheckedArr.push($($(\"input[name='size']\")[i]).val());\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			formData.append(\"size[]\", sizeCheckedArr);  //배열 전송\r\n");
      out.write("			\r\n");
      out.write("			//배열을 보내되, 더 줄여쓰는 코드를 작성(jquery)\r\n");
      out.write("			let colorCheckedArr=[];\r\n");
      out.write("			$.each($(\"input[name='color']:checked\"), function(){\r\n");
      out.write("				colorCheckedArr.push($(this).val());\r\n");
      out.write("			});\r\n");
      out.write("			formData.append(\"color[]\", colorCheckedArr);		\r\n");
      out.write("\r\n");
      out.write("			formData.append(\"detail\", $(\"#detail\").val());		\r\n");
      out.write("			\r\n");
      out.write("			for(let i=0;i<fileList.length;i++){\r\n");
      out.write("				let file=fileList[i];\r\n");
      out.write("				//파일뿐만 아니라 파라미터 등도 심을 수 있음\r\n");
      out.write("				formData.append(\"file\", file);  //(파라미터명, 어떤 파일)\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			//비동기방식으로 formData 를 전송\r\n");
      out.write("            //processData:false, --> 쿼리스트링화 방지 : 이미지는 쿼리스트링으로 전송할 수 없기 때문\r\n");
      out.write("            //application/x-www... --> contentType:false\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url:\"/admin/product/regist2.jsp\",\r\n");
      out.write("				type:\"post\",\r\n");
      out.write("				processData:false,  //쿼리리스트링 방지\r\n");
      out.write("				contentType:false,  //application//x-www 방지\r\n");
      out.write("				data:formData,\r\n");
      out.write("				success:function(result, status, xhr){\r\n");
      out.write("					alert(\"상품 등록 완료\");\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("	<script type=\"text/babel\">\r\n");
      out.write("		let tag=[];  //<ImgBox/> UI 컴포넌트를 누적할 배열  \r\n");
      out.write("		let previewRoot;  //react에 의해 랜더링될 컨테이너 요소 (onLoad할 때 메모리에 한번만 올림)\r\n");
      out.write("		let fileList=[];  //파일정보를 가진 배열 (일반배열)		 \r\n");
      out.write("		let oriFiles;  //원래 유저가 선택한 파일배열 원본 (readOlny)\r\n");
      out.write("\r\n");
      out.write("		//4)\r\n");
      out.write("		function removeImg(e, index){  \r\n");
      out.write("			//시각적인 삭제 처리\r\n");
      out.write("			$(e.target).parent().parent().remove();\r\n");
      out.write("			\r\n");
      out.write("			//X버튼 누를 경우 원본 배열에서 주소값(고유값)을 이용해 해당 파일을 추출 \r\n");
      out.write("			//왜? fileList.splice(index, 1) 인덱스에서 삭제할 경우 삭제마다 배열의 순서가 바뀌므로\r\n");
      out.write("			let file=oriFiles[index];\r\n");
      out.write("\r\n");
      out.write("			//추출한 파일이 삭제 대상의 배열에서 몇번째에 살고있는지 index 조사\r\n");
      out.write("			let sel_index=fileList.indexOf(file);  \r\n");
      out.write("\r\n");
      out.write("			//배열에서 삭제\r\n");
      out.write("			fileList.splice(sel_index, 1);   //console에서 fileList 확인\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		//UI 목록 반영\r\n");
      out.write("		function createCategoryTable(result) {\r\n");
      out.write("			let op = \"<option value='0'>상품분류 선택</option>\";\r\n");
      out.write("			for (let i = 0; i < result.length; i++) {\r\n");
      out.write("				let category = result[i];\r\n");
      out.write("				op += \"<option value='\"+category.category_idx+\"'>\"\r\n");
      out.write("						+ category.category_name + \"</option>\";\r\n");
      out.write("			}\r\n");
      out.write("			$(\"#category\").html(op);\r\n");
      out.write("		}\r\n");
      out.write("		//카테고리 목록 가져오기	\r\n");
      out.write("		function getCategoryList() {\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : \"/admin/category/category_list.jsp\",\r\n");
      out.write("				type : \"GET\",\r\n");
      out.write("				success : function(result, status, xhr) {\r\n");
      out.write("					console.log(result);\r\n");
      out.write("					//let categoryList=JSON.parse(result);\r\n");
      out.write("\r\n");
      out.write("					createCategoryTable(result); //목록 UI에 반영  //console 창에서 fileList 확인\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		//3) 파일 미리보기 - 사용자가 선택한 파일들을 매개변수로 받음\r\n");
      out.write("		function previewImg(){\r\n");
      out.write("			tag=[];\r\n");
      out.write("\r\n");
      out.write("			for(let i=0;i<fileList.length;i++){\r\n");
      out.write("				let reader=new FileReader();\r\n");
      out.write("				\r\n");
      out.write("				reader.onload=function(e){  //파일이 읽혀지면\r\n");
      out.write("					//e : 읽은 파일에 대한 정보가 들어있음\r\n");
      out.write("					//$(\"#preview\").html(\"<img src='\"+e.target.result+\"' width='100px'>\");  //react가 대신함\r\n");
      out.write("					tag.push(<ImgBox key={i} src={e.target.result} index={i} />);\r\n");
      out.write("					\r\n");
      out.write("					if(i>=fileList.length-1){  //마지막 이미지에 도달하면\r\n");
      out.write("						previewRoot.render(tag);\r\n");
      out.write("					}\r\n");
      out.write("				};\r\n");
      out.write("				reader.readAsDataURL(fileList[i]);  //(읽을 대상 파일)\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		$(function() {\r\n");
      out.write("			previewRoot = ReactDOM.createRoot(document.getElementById(\"preview\"));\r\n");
      out.write("			$(document).ready(function() {\r\n");
      out.write("				getCategoryList(); //카테고리 목록 가져오기\r\n");
      out.write("				\r\n");
      out.write("				$('#detail').summernote({\r\n");
      out.write("					height : 200\r\n");
      out.write("				});\r\n");
      out.write("				\r\n");
      out.write("				//5)등록 버튼에 이벤트 연결\r\n");
      out.write("				$(\"#bt_regist\").click(function(){\r\n");
      out.write("					regist();\r\n");
      out.write("				});\r\n");
      out.write("\r\n");
      out.write("				//목록 버튼에 이벤트 연결\r\n");
      out.write("				$(\"#bt_list\").click(function(){\r\n");
      out.write("					$(location).attr(\"href\", \"/admin/product/list.jsp\");\r\n");
      out.write("				});\r\n");
      out.write("\r\n");
      out.write("				//1) 파일에 이벤트 연결\r\n");
      out.write("				$(\"#file\").change(function(){\r\n");
      out.write("					this.files;  //파일컴포넌트에서 선택한 파일을 보유한 배열이며 이 배열은 readOnly\r\n");
      out.write("					console.log(\"당신이 선택한 파일 수는 \", this.files.length);\r\n");
      out.write("					\r\n");
      out.write("					//fileList=this.files;\r\n");
      out.write("\r\n");
      out.write("					//유저가 선택한 파일에 대한 정보를 배열로 얻기\r\n");
      out.write("					oriFiles=this.files;\r\n");
      out.write("\r\n");
      out.write("					//this.files는 이미 자바스크립트의 파일배열로써, 읽기만 가능함 따라서 수정가능한 배열이 되려면 this.files 안에 있는\r\n");
      out.write("					//File들을 꺼내서 일반배열로 옮겨버리면 됨\r\n");
      out.write("					for(let i=0;i<this.files.length;i++){\r\n");
      out.write("						fileList.push(this.files[i]);\r\n");
      out.write("					}\r\n");
      out.write("					previewImg();  //2) 파일 미리보기, this.files : 전역변수로 빼두었기 때문에 매개변수로 받을 필요가 없음\r\n");
      out.write("				});\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
