/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-01-11 09:06:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import board.domain.Board;
import board.repository.BoardDAO;

public final class content_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


	BoardDAO boardDAO=new BoardDAO();

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/inc/header_link.jsp", Long.valueOf(1673414732663L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("board.repository.BoardDAO");
    _jspx_imports_classes.add("board.domain.Board");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

	String board_idx=request.getParameter("board_idx");
	Board board=boardDAO.select(Integer.parseInt(board_idx));

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>상세보기</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- BootStrap  플러그인 -->\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.1/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Popper JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 편집기  플러그인 -->\r\n");
      out.write("<script src=\"https://cdn.ckeditor.com/ckeditor5/35.4.0/classic/ckeditor.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function edit(){\r\n");
      out.write("	$(\"#form1\").attr({\r\n");
      out.write("		\"action\":\"/board/update\",\r\n");
      out.write("		\"method\":\"post\",\r\n");
      out.write("		\"enctype\":\"multipart/form-data\"\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	$(\"#form1\").submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//미리보기 구현 (파일정보를 가진 obj 받기)\r\n");
      out.write("function preview(obj){\r\n");
      out.write("	//넘겨받은 파일 객체를 스트림으로 읽어 src에 대입\r\n");
      out.write("	let reader=new FileReader();\r\n");
      out.write("	\r\n");
      out.write("	//a->c->b\r\n");
      out.write("	//console.log(\"a\");\r\n");
      out.write("	reader.onload=function(e){\r\n");
      out.write("		//console.log(\"b\");\r\n");
      out.write("		//console.log(e);\r\n");
      out.write("		//console.log(e.target.result);\r\n");
      out.write("		$(\"#pic\").attr(\"src\", e.target.result);\r\n");
      out.write("	};\r\n");
      out.write("	reader.readAsDataURL(obj);\r\n");
      out.write("	//console.log(\"c\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("    ClassicEditor\r\n");
      out.write("        .create( document.querySelector( '#content' ) )\r\n");
      out.write("        .catch( error => {\r\n");
      out.write("            console.error( error );\r\n");
      out.write("        } );\r\n");
      out.write("    \r\n");
      out.write("	//버튼에 이벤트 연결\r\n");
      out.write("	$($(\"button\")[0]).click(function(){\r\n");
      out.write("		//alert(\"등록예정\");\r\n");
      out.write("		edit();\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	//버튼에 이벤트 연결\r\n");
      out.write("	$($(\"button\")[1]).click(function(){\r\n");
      out.write("		alert(\"목록보기\");\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	//버튼에 이벤트 연결\r\n");
      out.write("	$($(\"button\")[2]).click(function(){\r\n");
      out.write("		alert(\"목록보기\");\r\n");
      out.write("		loation.href=\"/board/list.jsp\";\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	$(\"#file\").on(\"change\", function(){\r\n");
      out.write("		//console.log(this.files[0]);\r\n");
      out.write("		preview(this.files[0]);\r\n");
      out.write("	});\r\n");
      out.write("});\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container mt-2\">\r\n");
      out.write("		<form id=\"form1\">\r\n");
      out.write("			<input type=\"hidden\" name=\"board_idx\" value=\"");
      out.print(board.getBoard_idx() );
      out.write("\">\r\n");
      out.write("			<input type=\"hidden\" name=\"filename\" value=\"");
      out.print(board.getFilename() );
      out.write("\">\r\n");
      out.write("			<div class=\"row text-center\">\r\n");
      out.write("				<h3>상세보기</h3>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row mt-2\">\r\n");
      out.write("				<input type=\"text\" class=\"form-control\" value=\"");
      out.print(board.getTitle() );
      out.write("\" name=\"title\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row mt-2\">\r\n");
      out.write("				<input type=\"text\" class=\"form-control\" value=\"");
      out.print(board.getWriter() );
      out.write("\" name=\"writer\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row mt-2\">\r\n");
      out.write("				<textarea style=\"width: 100%\" id=\"content\" name=\"content\" >");
      out.print(board.getContent() );
      out.write("</textarea>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row mt-2\">\r\n");
      out.write("				<img src=\"/data/");
      out.print(board.getFilename() );
      out.write("\" width=\"150\" id=\"pic\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row mt-2\">\r\n");
      out.write("				<input type=\"file\" class=\"form-control\" name=\"file\" id=\"file\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row my-2\">\r\n");
      out.write("				<div class=\"col text-center\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-outline-warning\">수정</button>\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-outline-warning\">삭제</button>\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-outline-warning\">목록</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
